/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareViktorVsChatgptRouteImport } from './routes/compare.viktor-vs-chatgpt'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareViktorVsChatgptRoute = CompareViktorVsChatgptRouteImport.update({
  id: '/compare/viktor-vs-chatgpt',
  path: '/compare/viktor-vs-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/creators': typeof CreatorsRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/impressum': typeof ImpressumRoute
  '/integrations': typeof IntegrationsRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/compare/viktor-vs-chatgpt': typeof CompareViktorVsChatgptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/creators': typeof CreatorsRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/impressum': typeof ImpressumRoute
  '/integrations': typeof IntegrationsRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/compare/viktor-vs-chatgpt': typeof CompareViktorVsChatgptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/creators': typeof CreatorsRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/impressum': typeof ImpressumRoute
  '/integrations': typeof IntegrationsRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/compare/viktor-vs-chatgpt': typeof CompareViktorVsChatgptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/brand'
    | '/case-studies'
    | '/changelog'
    | '/creators'
    | '/docs'
    | '/enterprise'
    | '/get-started'
    | '/impressum'
    | '/integrations'
    | '/landing'
    | '/pricing'
    | '/product'
    | '/security'
    | '/terms'
    | '/use-cases'
    | '/compare/viktor-vs-chatgpt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/brand'
    | '/case-studies'
    | '/changelog'
    | '/creators'
    | '/docs'
    | '/enterprise'
    | '/get-started'
    | '/impressum'
    | '/integrations'
    | '/landing'
    | '/pricing'
    | '/product'
    | '/security'
    | '/terms'
    | '/use-cases'
    | '/compare/viktor-vs-chatgpt'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/brand'
    | '/case-studies'
    | '/changelog'
    | '/creators'
    | '/docs'
    | '/enterprise'
    | '/get-started'
    | '/impressum'
    | '/integrations'
    | '/landing'
    | '/pricing'
    | '/product'
    | '/security'
    | '/terms'
    | '/use-cases'
    | '/compare/viktor-vs-chatgpt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  BrandRoute: typeof BrandRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ChangelogRoute: typeof ChangelogRoute
  CreatorsRoute: typeof CreatorsRoute
  DocsRoute: typeof DocsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GetStartedRoute: typeof GetStartedRoute
  ImpressumRoute: typeof ImpressumRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LandingRoute: typeof LandingRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
  CompareViktorVsChatgptRoute: typeof CompareViktorVsChatgptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/viktor-vs-chatgpt': {
      id: '/compare/viktor-vs-chatgpt'
      path: '/compare/viktor-vs-chatgpt'
      fullPath: '/compare/viktor-vs-chatgpt'
      preLoaderRoute: typeof CompareViktorVsChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  BrandRoute: BrandRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ChangelogRoute: ChangelogRoute,
  CreatorsRoute: CreatorsRoute,
  DocsRoute: DocsRoute,
  EnterpriseRoute: EnterpriseRoute,
  GetStartedRoute: GetStartedRoute,
  ImpressumRoute: ImpressumRoute,
  IntegrationsRoute: IntegrationsRoute,
  LandingRoute: LandingRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
  CompareViktorVsChatgptRoute: CompareViktorVsChatgptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
